// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function(root) {
    var Base, ButtonComponent, CheckableComponent, InputCollection, InputComponent, InputFactory, SelectComponent, camelize;
    camelize = function(str) {
      var camel;
      camel = str.replace(/(?:^|[-_ ])(\w)/g, function(_, c) {
        if (c) {
          return c.toUpperCase();
        } else {
          return "";
        }
      });
      return camel.charAt(0).toLowerCase() + camel.slice(1);
    };
    Base = (function() {
      function Base(el) {
        this.el = el;
        this.id = el.id;
        this.listeners = [];
        return this;
      }

      Base.prototype.value = function() {
        if (arguments.length) {
          this._setValue(arguments);
          return this;
        } else {
          if (this._hasValue() && this.isValid()) {
            return this._getValue();
          } else {
            return false;
          }
        }
      };

      Base.prototype.values = function() {
        return this.value(arguments);
      };

      Base.prototype.isValid = function() {
        return this.el.checkValidity();
      };

      Base.prototype.isFocused = function() {
        return document.activeElement === this.el;
      };

      Base.prototype.isDisabled = function() {
        return this.el.disabled;
      };

      Base.prototype.disable = function() {
        this.el.disabled = true;
        return this;
      };

      Base.prototype.enable = function() {
        this.el.disabled = false;
        return this;
      };

      Base.prototype._hasValue = function() {
        return !!this.el.value;
      };

      Base.prototype._setValue = function(value) {
        this.dispatchEvent(new Event("change"));
        return (this.el.value = value);
      };

      Base.prototype._getValue = function() {
        return this.el.value;
      };

      Base.prototype._checkable = function() {
        return "checked" in this.el;
      };

      Base.prototype.addEventListener = function(type, listener, useCapture) {
        if (useCapture == null) {
          useCapture = false;
        }
        listener = listener.bind(this);
        this.el.addEventListener(type, listener, useCapture);
        this.listeners.push({
          type: type,
          listener: listener
        });
        return this;
      };

      Base.prototype.removeEventListener = function(type, listener, useCapture) {
        if (useCapture == null) {
          useCapture = false;
        }
        this.el.removeEventListener(type, listener, useCapture);
        return this;
      };

      Base.prototype.dispatchEvent = function(event) {
        this.el.dispatchEvent(event);
        return this;
      };

      return Base;

    })();
    ButtonComponent = (function(_super) {
      __extends(ButtonComponent, _super);

      function ButtonComponent(el) {
        ButtonComponent.__super__.constructor.call(this, el);
      }

      return ButtonComponent;

    })(Base);
    InputComponent = (function(_super) {
      __extends(InputComponent, _super);

      function InputComponent(el) {
        InputComponent.__super__.constructor.call(this, el);
      }

      InputComponent.prototype.placeholder = function(param) {
        if (param) {
          this.el.placeholder = param;
          return this;
        } else {
          return this.el.placeholder;
        }
      };

      return InputComponent;

    })(Base);
    CheckableComponent = (function(_super) {
      __extends(CheckableComponent, _super);

      function CheckableComponent(el) {
        CheckableComponent.__super__.constructor.call(this, el);
      }

      CheckableComponent.prototype.check = function() {
        this._switch(true);
        return this;
      };

      CheckableComponent.prototype.uncheck = function() {
        this._switch(false);
        return this;
      };

      CheckableComponent.prototype.isChecked = function() {
        return this.el.checked;
      };

      CheckableComponent.prototype._switch = function(bool) {
        if (typeof bool === "undefined" || this.isChecked() !== bool) {
          this.el.checked = !this.el.checked;
          this.dispatchEvent(new Event("change"));
        }
        return this.isChecked();
      };

      CheckableComponent.prototype.value = function() {
        if (arguments.length) {
          return this._setValue(arguments);
        } else {
          if (this.isChecked()) {
            return CheckableComponent.__super__.value.call(this);
          } else {
            return false;
          }
        }
      };

      return CheckableComponent;

    })(Base);
    SelectComponent = (function(_super) {
      __extends(SelectComponent, _super);

      function SelectComponent(el) {
        SelectComponent.__super__.constructor.call(this, el);
      }

      SelectComponent.prototype.value = function() {
        var option;
        return (function() {
          var _i, _len, _ref, _results;
          _ref = this.selected();
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            option = _ref[_i];
            _results.push(option.value);
          }
          return _results;
        }).call(this);
      };

      SelectComponent.prototype.selected = function() {
        var options;
        options = this.el.querySelectorAll("option");
        return Array.prototype.filter.call(options, function(option) {
          return option.selected && !option.disabled;
        });
      };

      return SelectComponent;

    })(Base);
    InputCollection = (function(_super) {
      __extends(InputCollection, _super);

      function InputCollection(selector) {
        if (selector) {
          this.add(selector);
        }
        return this;
      }

      InputCollection.prototype.add = function(el) {
        var self;
        if (!el) {
          console.warn("Nothing passed to InputCollection::add");
          return false;
        }
        self = this;
        if (typeof el === "string") {
          return self.add(document.querySelectorAll(el));
        }
        if (el instanceof InputCollection) {
          return self.push(el);
        }
        if (el.length) {
          return Array.prototype.forEach.call(el, function(e) {
            return self.add(e);
          });
        }
        if (el instanceof Node) {
          return self.push(InputFactory(el));
        }
        if (el instanceof Base) {
          return self.push(el);
        }
        console.warn("Improper param passed to InputCollection::add");
        console.log(el);
        return false;
      };

      InputCollection.prototype.value = function() {
        var component, results, val;
        results = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = this.length; _i < _len; _i++) {
            component = this[_i];
            if (val = component.value()) {
              _results.push(val);
            }
          }
          return _results;
        }).call(this);
        if (results.length) {
          return results;
        } else {
          return false;
        }
      };

      InputCollection.prototype.values = function() {
        return this.value(arguments);
      };

      InputCollection.prototype.hashValue = function() {
        var component, results, val, _i, _len;
        results = {};
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          component = this[_i];
          val = component.value();
          results[camelize(component.id)] = val || "";
        }
        if (Object.keys(results).length) {
          return results;
        } else {
          return false;
        }
      };

      InputCollection.prototype.hashValues = function() {
        return this.hashValue(arguments);
      };

      InputCollection.prototype.isValid = function() {
        var component, _i, _len;
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          component = this[_i];
          if (!component.isValid()) {
            return false;
          }
        }
        return true;
      };

      InputCollection.prototype.addEventListener = function(type, listener, useCapture) {
        var component, _i, _len, _results;
        if (useCapture == null) {
          useCapture = false;
        }
        _results = [];
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          component = this[_i];
          _results.push(component.addEventListener(type, listener.bind(this), useCapture));
        }
        return _results;
      };

      InputCollection.prototype.dispatchEvent = function(type) {
        var component, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          component = this[_i];
          _results.push(component.dispatchEvent(type));
        }
        return _results;
      };

      InputCollection.prototype.componentById = function(id) {
        var component, _i, _len;
        if (id.charAt(0) === "#") {
          id = id.slice(1);
        }
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          component = this[_i];
          if (component.id === id) {
            return component;
          }
        }
        return false;
      };

      InputCollection.prototype.check = function(param) {
        return this._changeCheck(true, param);
      };

      InputCollection.prototype.uncheck = function(param) {
        return this._changeCheck(false, param);
      };

      InputCollection.prototype._changeCheck = function(onOff, param) {
        var input, _i, _len, _results;
        if (typeof param === "undefined") {
          _results = [];
          for (_i = 0, _len = this.length; _i < _len; _i++) {
            input = this[_i];
            if (input instanceof CheckableComponent) {
              _results.push(input[onOff ? "check" : "uncheck"]());
            }
          }
          return _results;
        } else if (typeof param === "number" && this[param] && this[param]._switch) {
          return this[param][onOff ? "check" : "uncheck"]();
        } else if (typeof param === "string") {
          if ((input = this.inputById(param))) {
            if (input instanceof CheckableComponent) {
              return input[onOff ? "check" : "f"];
            }
          }
        }
      };

      return InputCollection;

    })(Array);
    InputFactory = function(el) {
      var classMatcher, constructor;
      classMatcher = {
        input: {
          checkbox: CheckableComponent,
          radio: CheckableComponent
        },
        select: SelectComponent,
        button: ButtonComponent
      };
      if (typeof el === "string") {
        el = document.querySelectorAll(el);
      }
      if (el.length > 1) {
        return new InputCollection(el);
      } else {
        if (el.item) {
          el = el.item(0);
        }
        switch (el.tagName.toLowerCase()) {
          case "input" || "textarea":
            constructor = classMatcher.input[el.type] || InputComponent;
            return new constructor(el);
          case "select":
            constructor = classMatcher.select;
            return new constructor(el);
          case "button":
            constructor = classMatcher.button;
            return new constructor(el);
          default:
            console.warn("Invalid element passed to InputFactory");
            return false;
        }
      }
    };
    return root.InputJS = {
      Base: Base,
      InputComponent: InputComponent,
      SelectComponent: SelectComponent,
      CheckableComponent: CheckableComponent,
      ButtonComponent: ButtonComponent,
      InputCollection: InputCollection,
      InputFactory: InputFactory
    };
  })((function() {
    if (typeof exports !== "undefined") {
      return exports;
    } else {
      return window;
    }
  })());

}).call(this);
